  
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure.Annotations;

namespace EntrepotSchema
{
   public partial class Entrepot
   {
      partial void Init();

      /// <summary>
      /// Default constructor
      /// </summary>
      public Entrepot()
      {
         Init();
      }

      // Persistent properties

      /// <summary>
      /// Identity, Required, Indexed
      /// </summary>
      public int Id { get; set; }

   }
}


namespace EntrepotSchema
{
   public partial class EntrepotDatabaseInitializer : MigrateDatabaseToLatestVersion<Entrepot, EntrepotDbMigrationConfiguration>
   {
   }
}

namespace EntrepotSchema
{
   public sealed partial class EntrepotDbMigrationConfiguration : DbMigrationsConfiguration<Entrepot>
   {
      partial void Init();

      public EntrepotDbMigrationConfiguration()
      {
         AutomaticMigrationsEnabled = false;
         AutomaticMigrationDataLossAllowed = false;
         Init();
      }
   }
}


namespace EntrepotSchema
{
   public partial class Entrepot : System.Data.Entity.DbContext
   {
